"""empty message

Revision ID: 30a095288bca
Revises: f2f7b3e62287
Create Date: 2023-02-08 22:37:38.586579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30a095288bca'
down_revision = 'f2f7b3e62287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('puntuacion',
               existing_type=postgresql.ENUM('uno', 'dos', 'tres', 'cuatro', 'cinco', name='puntuaciones'),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('puntuacion',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('uno', 'dos', 'tres', 'cuatro', 'cinco', name='puntuaciones'),
               existing_nullable=True)

    # ### end Alembic commands ###
