"""empty message

Revision ID: 45ea0ef2bb6b
Revises: ba5338fc396f
Create Date: 2023-01-25 19:01:13.695333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ea0ef2bb6b'
down_revision = 'ba5338fc396f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntuacion', sa.Enum('uno', 'dos', 'tres', 'cuatro', 'cinco', name='puntuaciones'), nullable=True))
        batch_op.add_column(sa.Column('visita', sa.Enum('Pareja', 'Familia', 'Solo', 'Amigos', 'Negocios', name='visita_types'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('visita')
        batch_op.drop_column('puntuacion')

    # ### end Alembic commands ###
