"""empty message

Revision ID: 599033f6312d
Revises: 
Create Date: 2023-01-30 18:10:20.981828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599033f6312d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('customer', 'manager', name='type_types'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comercial_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('telf', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=700), nullable=False),
    sa.Column('cambiador', sa.Boolean(), nullable=True),
    sa.Column('trona', sa.Boolean(), nullable=True),
    sa.Column('accessible_carrito', sa.Boolean(), nullable=True),
    sa.Column('espacio_carrito', sa.Boolean(), nullable=True),
    sa.Column('ascensor', sa.Boolean(), nullable=True),
    sa.Column('productos_higiene', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('location')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', name='gender_types'), nullable=True),
    sa.Column('subscription', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comercial_place_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('puntuacion', sa.Enum('uno', 'dos', 'tres', 'cuatro', 'cinco', name='puntuaciones'), nullable=True),
    sa.Column('price', sa.Enum('Barato', 'Normal', 'Caro', name='price_types'), nullable=True),
    sa.Column('a_domicilio', sa.Enum('Si', 'No', name='a_domicilio_types'), nullable=True),
    sa.Column('mesa', sa.Enum('Si', 'No', name='mesa_types'), nullable=True),
    sa.Column('alcohol', sa.Enum('Si', 'No', name='alcohol_types'), nullable=True),
    sa.Column('visita', sa.Enum('Pareja', 'Familia', 'Solo', 'Amigos', 'Negocios', name='visita_types'), nullable=True),
    sa.ForeignKeyConstraint(['comercial_place_id'], ['comercial_places.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('comercial_place_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comercial_place_id'], ['comercial_places.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos_comercial_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comercial_place_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['comercial_place_id'], ['comercial_places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('rates_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('comercial_place_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Enum('1', '2', '3', '4', '5', name='rate_types'), nullable=False),
    sa.ForeignKeyConstraint(['comercial_place_id'], ['comercial_places.id'], ),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_comments')
    op.drop_table('rates_customers')
    op.drop_table('photos_comercial_place')
    op.drop_table('favorits')
    op.drop_table('comments')
    op.drop_table('managers')
    op.drop_table('customers')
    op.drop_table('comercial_places')
    op.drop_table('users')
    # ### end Alembic commands ###
