"""empty message

Revision ID: 677c781b5901
Revises: e7d76cb114ad
Create Date: 2023-01-22 11:34:05.092643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677c781b5901'
down_revision = 'e7d76cb114ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.drop_constraint('comercial_places_user_fkey', type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comercial_places_user_fkey', 'users', ['user'], ['id'])

    # ### end Alembic commands ###
