"""empty message

Revision ID: 70f2369ba4d7
Revises: 7275f59fc9dd
Create Date: 2023-01-21 12:16:58.267802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f2369ba4d7'
down_revision = '7275f59fc9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_user_fkey', type_='foreignkey')
        batch_op.drop_column('user')

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_constraint('managers_user_fkey', type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('managers_user_fkey', 'users', ['user'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('customers_user_fkey', 'users', ['user'], ['id'])

    # ### end Alembic commands ###
