"""empty message

Revision ID: 88a9078438a8
Revises: b6896f154efa
Create Date: 2023-02-22 11:38:36.056831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a9078438a8'
down_revision = 'b6896f154efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates_customers', schema=None) as batch_op:
        batch_op.drop_constraint('rates_customers_customer_fkey', type_='foreignkey')
        batch_op.drop_column('customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('rates_customers_customer_fkey', 'customers', ['customer'], ['id'])

    # ### end Alembic commands ###
