"""empty message

Revision ID: aa194922e552
Revises: bd026b1c4fb5
Create Date: 2023-01-23 19:28:25.481783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa194922e552'
down_revision = 'bd026b1c4fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
