"""empty message

Revision ID: bd026b1c4fb5
Revises: 677c781b5901
Create Date: 2023-01-22 11:43:03.387866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd026b1c4fb5'
down_revision = '677c781b5901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trona', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accessible_carrito', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('espacio_carrito', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ascensor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('productos_higiene', sa.Boolean(), nullable=True))
        batch_op.alter_column('cambiador',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('trono')
        batch_op.drop_column('childs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercial_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('childs', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('trono', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('cambiador',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('productos_higiene')
        batch_op.drop_column('ascensor')
        batch_op.drop_column('espacio_carrito')
        batch_op.drop_column('accessible_carrito')
        batch_op.drop_column('trona')

    # ### end Alembic commands ###
