import React, { useState, useEffect, useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Context } from "../store/appContext";
import imagen from "../../img/account.png";

export const Terminosdeuso = () => {

  return (
        <div className="container">
          <h6 className="">
          USO DE LOS SERVICIOS
          </h6>
          <p id="textoslegales">A modo de condición para utilizar los Servicios, usted garantiza que: (i) la información que suministre a través de los Servicios a las Empresas de Baby Friendly es veraz, precisa, actual y completa, (ii) si es Titular de una cuenta, protegerá la información de esta, y supervisará y se responsabilizará del uso que otras personas hagan de ella, (iii) tiene, como mínimo, 13 años (en algunas jurisdicciones, la legislación local puede exigir una edad superior), edad que le permite registrar una cuenta, usar los Servicios y hacer aportaciones a nuestros Sitios web, y (iv) dispone de autoridad legal para formalizar el presente Acuerdo y para utilizar los Servicios, incluidos nuestros Sitios web, de acuerdo con los términos y condiciones especificados en este documento. Las Empresas de Baby Friendly no recopilan conscientemente la información de ninguna persona que sea menor de 13 años. Nos reservamos el derecho, a nuestra entera discreción, de denegar a cualquier persona el acceso a los Servicios, en cualquier momento y por cualquier motivo, incluido, entre otros, el incumplimiento del presente Acuerdo. Al usar los Servicios, incluidos los productos o servicios que permiten compartir Contenido con los sitios de terceros, acepta que usted es el único responsable de la información que comparta con las Empresas de Baby Friendly. Puede acceder a los Servicios únicamente con la finalidad para la que se han concebido y según lo permitido en este Acuerdo.</p>
          <p id="textoslegales">Copiar, transmitir, reproducir, replicar, publicar o redistribuir (a) Contenido o parte de este o (b) los Servicios en general está terminantemente prohibido sin el consentimiento previo por escrito de las Empresas de Baby Friendly. Para solicitar tal consentimiento, envíe su petición a la siguiente dirección:</p>
          <p id="textoslegales">Director, Partnerships and Business Development Baby Friendly, LLC 400 1st Avenue Needham, MA 02494, USA:</p>
          <p id="textoslegales">Para poder acceder a ciertas funciones de los Servicios, deberá crear una cuenta y convertirse en su Titular. Al crearla, la información que proporcione deberá ser completa y exacta. Usted es el único responsable de la actividad que se produzca en ella como, por ejemplo, interacciones y comunicaciones que establezca con otras personas. Además, deberá protegerla en todo momento y mantener actualizados sus datos de contacto.</p>
          <p id="textoslegales">Si crea una cuenta de Baby Friendly con fines comerciales, y acepta el presente Acuerdo en nombre de una empresa, organización u otra entidad jurídica, manifiesta y garantiza que tiene la autorización para ello y también para que dicha entidad cumpla con las disposiciones del presente Acuerdo. En ese caso, los términos “usted” y “su” que se utilicen en este documento harán referencia a dicha entidad, y la persona que actúe en nombre de dicha empresa será el “Representante legal de la empresa”.</p>
          <p id="textoslegales">Al usar los Servicios, es posible que encuentre enlaces a sitios y aplicaciones de terceros o que pueda interactuar con ellos, por ejemplo, compartiendo Contenido desde los Servicios, incluido el suyo, con dichos sitios y aplicaciones de terceros. Tenga en cuenta que los sitios y aplicaciones de terceros pueden publicar el Contenido que comparta. Es posible que estos terceros cobren una tarifa por el uso de determinados servicios o contenidos que proporcionen en sus sitios web o a través de estos. Por lo tanto, deberá realizar todas las comprobaciones que considere necesarias o apropiadas antes de llevar a cabo cualquier tipo de transacción con un tercero para determinar si incurrirá en un cargo. Las tarifas o los cargos relativos a dicho contenido o servicios de terceros que puedan indicar las Empresas de Baby Friendly son meramente informativos. Las interacciones que realice con sitios y aplicaciones de terceros quedan bajo su responsabilidad. Por el presente documento, reconoce y acepta expresamente que las Empresas de Baby Friendly no son responsables en modo alguno de dichos sitios o aplicaciones de terceros.</p>
          <p id="textoslegales">Parte del Contenido que se muestra en los Servicios o a través de estos se utiliza para fines comerciales. Asimismo, acepta y reconoce que las Empresas de Baby Friendly pueden incluir publicidad y promociones en los Servicios, al lado o cerca de su Contenido o el de otras personas, o próximo a este de algún otro modo. Por ejemplo, en el caso de vídeos u otro contenido dinámico, la publicidad o las promociones podrían aparecer antes, durante o después de su presentación.</p>
          <h6 className="">
          PRODUCTOS ADICIONALES
          </h6>
          <p id="textoslegales">Si las Empresas de Baby Friendly lo estiman oportuno, pueden modificar, actualizar o dejar de ofrecer determinados productos y funciones de los Servicios. En virtud del presente Acuerdo, reconoce y acepta que las Empresas de Baby Friendly no tienen obligación alguna de almacenar o mantener su Contenido u otra información que proporcione, salvo que así lo exija la legislación aplicable.</p>
          <p id="textoslegales">Ofrecemos otros servicios que también pueden estar regidos por términos o acuerdos adicionales. Si utiliza tales servicios, tendrá a su disposición las condiciones adicionales, las cuales pasarán a formar parte de este Acuerdo salvo en los casos en que lo excluyan de forma expresa o lo sustituyan de algún otro modo. Por ejemplo, si usa o compra tales servicios adicionales con fines comerciales o empresariales, deberá aceptar las correspondientes condiciones adicionales. En la medida en que otras condiciones entren en conflicto con los términos y condiciones de este Acuerdo, prevalecerán las condiciones adicionales en lo relativo al conflicto con dichos servicios.</p>
          <h6 className="">
          POLÍTICA DE PRIVACIDAD Y DIVULGACIÓN DE INFORMACIÓN.
          </h6>
          <p id="textoslegales">La información personal que publique en los Servicios o que envíe en relación con estos se usará de acuerdo con lo estipulado en nuestra política de privacidad. Haga clic en este enlace para leer nuestra política de privacidad.</p>
          <h6 className="">
          OPINIONES, COMENTARIOS Y USO DE OTRAS ÁREAS INTERACTIVAS; CONCESIÓN DE LICENCIAS
          </h6>
          <p id="textoslegales">sus comentarios siempre son bienvenidos. Tenga en cuenta que, al proporcionar su Contenido en los Servicios o a través de estos, ya sea enviándolo por correo electrónico, publicándolo en algún producto de sincronización de Baby Friendly o a través de los servicios y aplicaciones de un tercero, o al incluir Contenido suyo, o parte de este, que se transmite a su cuenta de Baby Friendly en virtud de algún producto, servicio, opinión, pregunta, foto, vídeo, comentario, sugerencia, idea de las Empresas de Baby Friendly o similar incluido en su Contenido, otorga a dichas empresas una licencia no exclusiva, libre de derechos de autor, perpetua, transferible, irrevocable y susceptible de someterse a otras licencias para (a) alojar, usar, reproducir, modificar, ejecutar, adaptar, traducir, distribuir, publicar, crear obras derivadas, y mostrar y representar públicamente su Contenido ante el mundo en cualquier formato y por cualquier medio conocido o que se conciba en el futuro; (b) ofrecer su Contenido al resto del mundo y que otros hagan lo mismo; (c) proporcionar, promocionar y mejorar los Servicios, así como poner a disposición de otras empresas, organizaciones o personas el Contenido de su propiedad que haya compartido en los Servicios para sindicarlo, retransmitirlo, distribuirlo, promocionarlo o publicarlo en otros medios y servicios, en virtud de nuestra política de privacidad y de este Acuerdo, y para (d) usar el nombre o la marca comercial que envíe asociado a su Contenido. Por el presente documento, acepta que Baby Friendly decida, a su entera discreción, si va a reconocerle como autor de su Contenido. También otorga a las Empresas de Baby Friendly el derecho de perseguir ante la ley a cualquier persona o entidad que infrinja sus derechos o los de dichas empresas en el Contenido por incumplimiento del presente Acuerdo. Reconoce y acepta que su Contenido no es confidencial ni de su propiedad. Afirma, manifiesta y garantiza que es el propietario de su Contenido o de que cuenta con las licencias, derechos (incluidos el copyright y cualesquiera otros derechos de propiedad intelectual), consentimientos y permisos necesarios para publicarlo y usarlo de cualquier otra forma (tanto usted como las Empresas de Baby Friendly), tal y como se autoriza en virtud de este Acuerdo.</p>
                  </div>
  );
};
